A Basic Implementation of DBZ checker
Veridise/Vanguard pull request #104
Opened 2023-05-08 11:19 UTC by wcphkust

Hi @0xddom and @kferles 

I implemented a basic version of DBZ (divide-by-zero) checker. It can detect the DBZ bug in the following tiny program:

```
pragma circom 2.0.0;

template Edwards2Montgomery() {
  signal input in[2];
  signal output out[2];
  out[0] <-- (1 + in[1]) / (1 - in[1]);
  out[1] <-- out[0] / in[0];
  out[0] * (1-in[1]) === (1 + in[1]);
  out[1] * in[0] === out[0];
}

component main = Edwards2Montgomery();
```

Here is the output of the checker after running the command `Vanguard --vanguard-domain circuit --detectors dbz $CIRCOMIR_PATH/DBZ_testcase01.ll`:

```
starting
Running detector: dbz
        Collect Global Variables
[Source] AddrVFGNode ID: 21 AddrStmt: [Var88 <-- Var89] 
   %initial.in.input = alloca [2 x i128]*, align 8 
[Sink] BinaryOPVFGNode ID: 126 PAGEdge: [118 = Binary(117, 114, )]          %sub = sub i128 1, %read.in.input6 
[Sink] LoadVFGNode ID: 71 LoadStmt: [Var128 <-- Var127] 
   %read.in.input12 = load i128, i128* %array_getter11, align 4 
Analysing slice:21)

Guard computation for slice:21)
onReachable
=============== DBZ  REPORTS ===============
In component Edwards2Montgomery the following input signals can cause a dbz bug:
  - in
==========================================
```

I omit the intermediate log consoled by the taint engine because it is so verbose.

I am not sure whether the checker is fully implemented, as I might forget several subcases. If so, please inform me and I will polish the implementation. :)

2023-05-08 12:53 UTC, 0xddom requested changes
Overall looks good for the reachability part. Lets take the ideas here for the graphs as we discussed earlier and then we can merge as a first iteration of the detector.

2023-05-08 12:53 UTC, 0xddom commented on lib/detectors/DBZ/DBZ.h
> +            std::cout << "=============== DBZ  REPORTS ===============\n";
This will need to be updated to the new reporting API, but I did not tell you about it so its ok for now.

2023-05-08 12:53 UTC, 0xddom commented on lib/detectors/DBZ/DBZ.h
> +            this->runDBZAnalysis(component,
nit: Is it necessary to use `this` here?

2023-05-08 15:58 UTC, kferles requested changes
Only added to the conversation started by Daniel. If our current API can handle the pattern matching, we should prefer it over LLVM's API.

2023-05-08 15:58 UTC, kferles commented on lib/detectors/DBZ/DBZ.h
> +            for (auto& BB : *(component->getLogic()->unwrap())) {
To add to that, this part shouldn't even depend on LLVM's API. Don't our wrappers have a similar API?

2023-05-08 17:28 UTC, wcphkust commented on lib/detectors/DBZ/DBZ.h
> +            this->runDBZAnalysis(component,
I have fixed it.

2023-05-08 17:29 UTC, wcphkust commented
I have removed the LLVM API for the iteration. However, after the refactoring, the detector fails to report the bug. I could not figure out which parts are not equivalent in the refactoring.

2023-05-08 20:12 UTC, kferles commented
@0xddom: Can you help @wcphkust with the Vanguard issue mentioned above?

2023-05-09 02:22 UTC, Technius commented
Please add a lit test that checks whether the detector is working correctly. In addition to helping debug, it also helps catch errors that might occur on different machines. See examples here: https://github.com/Veridise/Vanguard/tree/v1/test/circom

2023-05-09 07:58 UTC, 0xddom commented on lib/detectors/DBZ/DBZ.h
> +            virtual void visit(const UnknownIns <Domain> &v) {
```suggestion
            virtual void visit(const BinaryOpIns <Domain> &v) {
```

There are several classes that wrap instructions used depending on the subjacent llvm instruction. For the instructions you want I think you need to use `BinaryOpIns`

2023-05-09 08:04 UTC, 0xddom commented on lib/detectors/DBZ/DBZ.h
> +                if (auto bop = llvm::dyn_cast<llvm::BinaryOperator>(values.at(i))) {
You could also put this statement inside the query class and make it only return `IntDivRem` instructions

2023-05-09 15:27 UTC, wcphkust commented on lib/detectors/DBZ/DBZ.h
> +                if (auto bop = llvm::dyn_cast<llvm::BinaryOperator>(values.at(i))) {
OK. I have polished it. The current implementation can detect the bug correctly.

2023-05-09 15:48 UTC, 0xddom commented
Ok, good! I think the Constraints and Dataflow graph implementations can be made in another PR and we merge this one after we add tests to it. @kferles what do you think?

2023-05-09 15:50 UTC, kferles commented
Yes, definitely! Let's do separate PRs for those.

2023-05-09 17:42 UTC, wcphkust commented
I have removed `NDD.h` but I do not know how to add a lit test to check this detector

2023-05-11 16:09 UTC, 0xddom commented
The reporting lgtm

2023-05-11 16:09 UTC, 0xddom approved these changes

2023-05-11 16:40 UTC, kferles approved these changes

2023-05-11 16:55 UTC, merged