A Basic Implementation of DCD checker
Veridise/Vanguard pull request #110
Opened 2023-05-25 12:28 UTC by wcphkust

Hi @kferles and @0xddom,

I implemented a basic version of the DCD (Dataflow-Constraint Discrepancy) checker. The design of the DCD checker consists of the following components.

- Compute the data-flow reachability over all the values based on the taint analysis engine.
- Compute the data-flow reachability between the values and LHS/RHS values of constraints. For each constraint, we compute the constraint reachability of the values reaching the LHS/RHS.
- Considering the load/store instructions, convert the data-flow/constraint values to the addresses (of input/output) storing them.
- Diff the data-flow reachability and constraint reachability over input/output values, which yield a relation indicating the dataflow-constraint discrepancy.

In the implementation, the third component is fused into the first two parts, which correspond to the method `runDFRAnalysis` and `runCRAnalysis`, respectively.

Based on the above design, Vanguard can detect the DCD bug in the following tiny program:

```
pragma circom 2.0.0;

template SingleAssignment0() {
  signal input a;
  signal input b;
  signal output out;
  out <-- a + 1;
  out === b + 1;
}
component main = SingleAssignment0();
```

Here is the output of the checker after running the command `Vanguard --vanguard-domain circuit --detectors dcd $CIRCOMIR_PATH/dcd_buggy.ll`:

```
========================
 1 DCD signal detected: 
========================
A potential DCD in SingleAssignment0 is caused by: 
--------------------------------------------------------------------------------
  * Signals: initial.a.input and initial.out.output
--------------------------------------------------------------------------------
```

The above simple test case has been uploaded to the test directory.

Remark: Currently our implementation cannot support array signals. Given current IR as input, I think it is not difficult to polish the detector to support them. I have not started this part as @0xddom said the IR translator will be upgraded and the input form might be changed.

2023-05-26 11:38 UTC, 0xddom requested changes

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +                        if (std::find(inputValues.begin(), inputValues.end(), value1) != inputValues.end() ||
This block is duplicated below. Extract it into a function to avoid duplication. Same with the conditionals that use `std::find`. Extracting those predicates will make the code more readable. I drafted a couple example implementations here https://godbolt.org/z/xfMMEEGEr

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +                        if (signalValue1 != nullptr && signalValue2 != nullptr) {
```suggestion
                        if (signalValue1 && signalValue2) {
```

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +                    }
Duplicate code here too. Can be abstracted in a function.

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +                        }
And here we have the same pattern as in `runDFRAnalysis`. More reasons to extract this block in a function

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +                        if (signalValue1 != nullptr && signalValue2 != nullptr) {
```suggestion
                        if (signalValue1 && signalValue2) {
```

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +        void runDFRAnalysis(typename Domain::Component *component, ValueVec focusValues, ValueVec inputValues, ValueVec outputValues) {
This function should be extracted in its own class as an analysis for reusability.

`void runDFRAnalysis(...)` -> `class DRFAnalysis { void run(...) }`

2023-05-26 11:38 UTC, 0xddom commented on lib/detectors/DCD/DCD.h
> +        void runCRAnalysis(typename Domain::Component *component, ValueVec focusValues, ValueVec inputValues, ValueVec outputValues) {
This function should be extracted to a class as well.

2023-05-26 12:16 UTC, wcphkust commented on lib/detectors/DCD/DCD.h
> +        void dumpReachability(typename Domain::Component *component) {
It is just debugging. But I think it would be useful to help understand the reachability relation between the signals.

2023-05-28 15:18 UTC, wcphkust commented on lib/detectors/DCD/DCD.h
> +                        if (std::find(inputValues.begin(), inputValues.end(), value1) != inputValues.end() ||
I have refactored all the other parts except this one. I think it is a good practice to avoid duplication, while too many abstractions with such a short function would make us define many helper functions in various modules. Although the code line is a bit long, I don't think the code is hard to understand. Personally speaking, the functions of a class should explicitly reflect the key operations/functionalities. Over-abstraction is not a good choice in some cases, I think.

2023-05-29 11:16 UTC, 0xddom approved these changes
LGTM

2023-05-29 11:23 UTC, merged