nix + CI
Veridise/Vanguard pull request #17
Opened 2022-08-31 22:16 UTC by momo-ai

attempt at solang x86 addition and add to libVanguard
-- no changes made to CMake set path (do we want to reorganize the files/overlays to a central repo)
rust-preprocessor python outline
solidity-preprocessor attempt mirroring solc-typed-ast

2022-08-31 22:50 UTC, Technius commented on flake.nix
> +        solidity-preprocessor = pkgs.callPackage ./nix/solidity-preprocessor { inherit pkgs; };
This should go in the overlays section, so that `solidity-preprocessor` will be added to `pkgs` automatically.

`with final; pkgs.callPackage ./nix/solidity-preprocessor {} ;`

Basically, the above line will 1) bring all packages in `final` into scope; and 2) call `./nix/solidity-preprocessor {}` and automatically supply the arguments in scope.

2022-08-31 22:50 UTC, Technius commented on flake.nix
> +          # solidity-preprocessor.solidity-preprocessor RIGHT DONT NEED THIS HERE ?
This should just be `pkgs.solidity-preprocessor` after it is added to the overlay.

2022-09-08 18:28 UTC, Technius requested changes

2022-09-08 18:28 UTC, Technius commented on .github/workflows/ci.yml
>            echo "Done."
should also build `solang`, `solidity-preprocessor`, and `rust-preprocessor`.

2022-09-08 18:28 UTC, Technius commented on result
> +/nix/store/l0dm6pd9m8z99mms1ngda4frgk634sgn-rust-preprocessor
This file should be removed.

2022-09-08 18:28 UTC, Technius commented on source/README.md
> +# RustPreprocessor
These files should be removed.

2022-09-08 18:28 UTC, Technius commented on rust-preprocessor.nix
> +  mkdir -p $out/bin/rust-preprocessor
```suggestion
  mkdir -p $out/bin
```

2022-09-08 18:29 UTC, Technius commented on .github/workflows/ci.yml
> +          python3 run.py --src_path test/PuppetPool.sol  --detector irValidator
The run.py step should be commented out until we fix run.py.

2022-09-08 20:01 UTC, momo-ai commented on result
> +/nix/store/l0dm6pd9m8z99mms1ngda4frgk634sgn-rust-preprocessor
rm -rf /nix/store/l0dm6pd9m8z99mms1ngda4frgk634sgn-rust-preprocessor

2022-09-08 20:02 UTC, Technius commented on result
> +/nix/store/l0dm6pd9m8z99mms1ngda4frgk634sgn-rust-preprocessor
No, I meant that you should delete `result` and `source`.

2022-09-08 23:24 UTC, Technius commented on solang.nix
> +      };
Build fails because `x86_64-linux` is missing, I think we also need:
```
x86_64-linux = {
  url = "https://github.com/hyperledger/solang/releases/download/v0.1.12/solang-linux-x86-64";
  sha256 = "sha256-Mx7PjmzMU98gDH0fOxANpTgAj5nOT5mbTyT2ixcV068=";
}
```

2022-09-16 23:03 UTC, closed without merging