Support for circom
Veridise/Vanguard pull request #41
Opened 2022-12-12 22:21 UTC by 0xddom

Since I have already a hefty amount of code for supporting circom Im creating this pull request to start reviewing.

@Technius, the file you care about is `nix/svf/compile-flags.patch`.

2022-12-12 22:44 UTC, Technius commented on aux-build-scripts/build-svf.sh
> +rm -rf ${SCRIPT_DIR}/SVF  # Remove whatever is there to make sure we always get a fresh copy
```suggestion
rm -rf "${SCRIPT_DIR}"/SVF  # Remove whatever is there to make sure we always get a fresh copy
```

2022-12-12 22:44 UTC, Technius commented on aux-build-scripts/build-svf.sh
> +cd ${SCRIPT_DIR}/SVF || die "Failed to cd into ${SCRIPT_DIR}/SVF"
```suggestion
cd "${SCRIPT_DIR}"/SVF || die "Failed to cd into ${SCRIPT_DIR}/SVF"
```

2022-12-12 22:44 UTC, Technius commented on aux-build-scripts/build-svf.sh
> +rm -rf ${SCRIPT_DIR}/SVF  # Cleanup
```suggestion
cd "${SCRIPT_DIR}" || die "Failed to cd into ${SCRIPT_DIR}"
rm -rf "${SCRIPT_DIR}"/SVF  # Cleanup
```

2022-12-12 22:44 UTC, Technius commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +            analysis = new TaintAnalysis();
Would be better to use `std::unique_ptr` and `std::make_unique` to reduce the chance of introducing memory errors.

2022-12-12 22:44 UTC, Technius commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +                for (auto component : unit->components())
nit: explicitly indicating pointer on auto helps with readability
```suggestion
            for (auto *unit : universe.units())
                for (auto *component : unit->components())
```

2022-12-12 22:44 UTC, Technius commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +                for (auto signal : signals) {
nit:
```suggestion
                for (auto *signal : signals) {
```

2022-12-12 22:44 UTC, Technius commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +            end:
nit: can avoid the goto by using `break;`

2022-12-12 22:44 UTC, Technius commented on lib/domain/libCircuit/CircuitSummaryReader.cpp
> +#define HALO2_FRAMEWORK "halo2"
nit: may be better to define these as `constexpr auto` so they can be better handled by IDE, type checker, etc.

2022-12-12 22:44 UTC, Technius commented on lib/domain/libCircuit/CircuitSummaryReader.h
> +        CircuitModel<CircuitDomain> *model;
Since these seem to be owned by the `CircuitSummaryReader`, would be better to define these as `std::unique_ptr` to avoid potential memory safety issues.

2022-12-12 22:44 UTC, Technius commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +            }
nit: I don't think this is needed; `std::map::operator[]` will initialize the entry at the given index if it does not exist yet.

2022-12-12 22:44 UTC, Technius commented on lib/domain/libCircuit/langs/circom/CircomModel.h
> +                auto llvmInst = llvm::dyn_cast<llvm::GetElementPtrInst>(v.unwrap());
nit: `llvm::dyn_cast` returns null if it is not the given type, so this could be more cleanly expressed as:
```suggestion
                auto llvmInst = llvm::dyn_cast<llvm::GetElementPtrInst>(v.unwrap());
                if (!llvmInst) return;
```

2022-12-12 22:44 UTC, Technius commented on lib/domain/libCircuit/langs/circom/CircomUtils.cpp
> +#define METADATA_SUFFIX "_metadata"
nit: can avoid macros by instead using defining as `constexpr auto`

2022-12-12 22:44 UTC, Technius commented on nix/svf/compile-flags.patch
> +-            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS} -O0 -fno-rtti")
Just curious, what was the issue with RTTI?

2022-12-13 03:46 UTC, kferles requested changes
Need some work, but ok overall. Let's make sure it compiles in the actions before merging.

In the future, let's aim for smaller PRs. It would make both of our lives easier.

2022-12-13 03:46 UTC, kferles commented on lib/Vanguard.cpp
> +            std::string summary = filename;
Lines 270 - 283 are shared between Circuits and Blockchain domains. Let's extract a function and call it in both places.

2022-12-13 03:46 UTC, kferles commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +        std::cerr << "[DEBUG] Starting worklist algorithm (src=" << src << ") (trg=" << trg << ")" << std::endl;
Let's use a logging framework. If I am not mistaken, @Technius has used LLVM's logging API in other places. Since we are sticking with LLVM for the foreseeable future, I am okay with using that.

2022-12-13 03:46 UTC, kferles commented on lib/domain/libCircuit/ComputableUnit.h
> +            return nullptr;
This feels wrong.

2022-12-13 03:46 UTC, kferles commented on nix/svf/compile-flags.patch
> +-            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS} -O0 -fno-rtti")
It wouldn't let us derive from an SVF class because it couldn't find the type information.

2022-12-13 11:05 UTC, 0xddom commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +                for (auto component : unit->components())
I didn't knew you could do that. I will keep it in mind from now on

2022-12-13 11:07 UTC, 0xddom commented on lib/detectors/UnderConstraints/UnderConstraints.h
> +            end:
This was done for logging debug output, that function should just return there

2022-12-13 12:38 UTC, 0xddom commented
CI fails because of syntax, not sure why

2022-12-13 12:48 UTC, 0xddom commented on lib/domain/libCircuit/ComputableUnit.h
> +            return nullptr;
Because it is. That was a left over from when I was figuring out the `Domain` class model. `ComputableUnit` is no longer a subclass of `ObjectType`. It does not need to be.

2022-12-13 17:21 UTC, kferles commented on lib/domain/libCircuit/InputSignal.h
> +    class Circuit<Base, Domain>::InputSignal : public Circuit<Base, Domain>::template Signal<Wrap, D> {
The issue with the build might be that InputSignal is inheriting from a template class. I am not sure why we need that in the first place.

2022-12-13 18:00 UTC, 0xddom commented on lib/domain/libCircuit/InputSignal.h
> +    class Circuit<Base, Domain>::InputSignal : public Circuit<Base, Domain>::template Signal<Wrap, D> {
What I dont get is why it builds with clang and not with gcc

2022-12-13 18:02 UTC, 0xddom commented on lib/domain/libCircuit/InputSignal.h
> +    class Circuit<Base, Domain>::InputSignal : public Circuit<Base, Domain>::template Signal<Wrap, D> {
Also the whole Type and Value modules are based around inheritance of template classes, I dont see why is that an issue?

2022-12-13 18:09 UTC, kferles commented on lib/domain/libCircuit/InputSignal.h
> +    class Circuit<Base, Domain>::InputSignal : public Circuit<Base, Domain>::template Signal<Wrap, D> {
We had similar issues in the past, where clang is more permissive around templates. @stephensj2: do you have any suggestions on how to resolve this?

2022-12-13 18:21 UTC, Technius commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +        std::cerr << "[DEBUG] Starting worklist algorithm (src=" << src << ") (trg=" << trg << ")" << std::endl;
I don't think there is a big problem with adding third-party libraries to this project, because Vanguard is licensed under GPLv3. Spdlog is good, but we could probably get by without it for now.

2022-12-13 18:22 UTC, 0xddom commented on lib/domain/libCircuit/InputSignal.h
> +    class Circuit<Base, Domain>::InputSignal : public Circuit<Base, Domain>::template Signal<Wrap, D> {
From what I could gather from the internet the issue could be a circular dependecy. But I havent found it yet

2022-12-13 19:25 UTC, 0xddom commented on lib/domain/libCircuit/CircuitSummaryReader.h
> +        CircuitModel<CircuitDomain> *model;
This two pointers are passed around to the visitor classes and finally returned as part of the summary. I think a shared pointer would be better in this case

2022-12-14 00:14 UTC, Technius commented on lib/domain/libCircuit/CircuitSummaryReader.h
> +        CircuitModel<CircuitDomain> *model;
If I understand correctly, `langFactory` and `model` are allocated by `readSummary`, but they do not appear to be used elsewhere.

2022-12-14 00:14 UTC, Technius commented on lib/domain/libCircuit/CircuitSummaryReader.cpp
> +            langFactory = new CircomFactory(CircuitDomain::Factory::instance());
Won't this leak memory if `readSummary` is called twice?

2022-12-14 00:21 UTC, Technius commented on lib/Vanguard.cpp
> +    llvm::dbgs() << "Read summary from: " << summary << "\n";
Quick note: ideally we would `#define DEBUG_TYPE "vanguard"` at the top of the file and wrap the debug code in `LLVM_DEBUG({ llvm::dbgs() << "foo\n"; });` blocks. This will allow us to add an LLVM opt flag like `-debug` to enable debug output; however this functionality requires us to either 1) build LLVM with assertions & ABI breaking checks enabled; or 2) create a custom debug flag and set `llvm::DebugFlag = true` (see `llvm/Support/Debug.h`).

2022-12-14 10:29 UTC, 0xddom commented on lib/domain/libCircuit/CircuitSummaryReader.cpp
> +            langFactory = new CircomFactory(CircuitDomain::Factory::instance());
Technically yes, but `readSummary` is private and is called from the constructor. So while not enforced there is only one instance of each pointer per `CircuitSummaryReader` instance

2022-12-19 21:47 UTC, kferles requested changes
Once we address these and fix the output signal stuff, I believe we can merge and start prototyping detectors.

2022-12-19 21:47 UTC, kferles commented on lib/domain/libCircuit/langs/circom/CircomModel.h
>  #define setAndFailIfNull(v, e) v = e; if (v == nullptr) return nullptr
I would suggest getting rid of macros. If this is an assumption for correctness, then let's add assertions here.

2022-12-19 21:47 UTC, kferles commented on lib/domain/libCircuit/langs/circom/CircomSearchers.h
> +    std::optional<Result> searchOne(typename Domain::Function *func, InstructionClassQuery<Domain, Result> &searchQuery) {
Is the intention here to stop after we find the first match? If so, let's rename the function to "findFirst". Similar to "findAll" for "searchMany".

2022-12-19 21:47 UTC, kferles commented on lib/domain/libCircuit/langs/circom/CircomModel.h
> +#if 0
Should this preprocessor branch be removed?

2022-12-20 09:06 UTC, 0xddom commented on lib/domain/libCircuit/langs/circom/CircomSearchers.h
> +    std::optional<Result> searchOne(typename Domain::Function *func, InstructionClassQuery<Domain, Result> &searchQuery) {
Could be. The responsibility of what is returned falls onto the query object. From the function's perspective it will return either the first value returned by the query or all the query could find, so I can see either set of names.

Also, I think this two functions could be part of the `Domain::Function` class and the specialised visitor added to `Instruction.h` with its parent class. This way others could benefit from the API as it is general enough.

2022-12-20 10:42 UTC, 0xddom commented
@kferles All done from my side

2022-12-21 19:19 UTC, kferles approved these changes

2022-12-21 19:22 UTC, kferles commented
Why did we merge v1 circom-llvm-testing? Shouldn't it go the other way around? I am not sure what would be the consequences of this. Other than that, it's fine to merge by me. @stephensj2: are you ok with merging into v1?

2022-12-22 12:22 UTC, 0xddom commented
Yeah, there was a merge conflict in Vanguard.cpp that I had to address

2022-12-22 12:24 UTC, merged