Under constrained output detector [VAN-114]
Veridise/Vanguard pull request #44
Opened 2023-01-03 11:26 UTC by 0xddom

2023-01-04 12:17 UTC, 0xddom commented
@kferles nobug.circom and bug.circom pass but condbug.circom does not.

I'm thinking that maybe we should encode this as unit tests and start prototyping an architecture that make detectors testeable. I think we just need to create a separate layer for presentation (i.e printing to stderr) that we can mock in unit tests. Questions is, a different PR or in this PR?

2023-01-04 16:50 UTC, 0xddom commented
We seem to hit a global even with the change we did yesterday. And I'm not sure why

2023-01-05 17:04 UTC, 0xddom commented
Only thing missing are e2e tests with `lit`. Code is ready.

2023-01-10 20:37 UTC, kferles requested changes
Looks good in general. Just a few minor things.

2023-01-10 20:37 UTC, kferles commented on aux-build-scripts/build-pyul.sh
> +git checkout bryan/fix-llvm-dep
I think this has been merged into main now.

2023-01-10 20:37 UTC, kferles commented on lib/analysis/taint-analysis/TaintAnalysis.h
> +        void onUnreachable(SVF::ProgSlice *slice) override {
Why do both reachable and unreachable pairs are stored on the same map?

2023-01-10 20:37 UTC, kferles commented on lib/domain/libCircuit/langs/circom/CircomModel.h
> +//        int signalNameToIndex(const std::string& signalName, llvm::NamedMDNode *metadata) {
If we no longer need this, let's delete it.

2023-01-10 20:37 UTC, kferles commented on lib/domain/libCircuit/langs/circom/CircomSearchers.h
> +//        void visit(const UnknownIns<Domain> &v) override {
Same here! Delete if not needed.

2023-01-10 20:37 UTC, kferles commented on vanguard_driver.py
> +def run_detector_on_ll(detector: str, summary: Path, out_dir: Path) -> Dict[str, str]:
why do we need separate functions for bc and ll?

2023-01-10 20:40 UTC, 0xddom commented on vanguard_driver.py
> +def run_detector_on_ll(detector: str, summary: Path, out_dir: Path) -> Dict[str, str]:
Because of the glob. It searches `*_deploy.bc` files instead of `*.ll`. Maybe it can be implemented with a postfix argument for the extension instead than 2 separate functions.

2023-01-10 20:41 UTC, 0xddom commented on lib/analysis/taint-analysis/TaintAnalysis.h
> +        void onUnreachable(SVF::ProgSlice *slice) override {
Because this observer just collects all the slices. An unreachable slice will not have sinks, which is the part I care about in the detector.

2023-01-10 20:41 UTC, 0xddom commented on aux-build-scripts/build-pyul.sh
> +git checkout bryan/fix-llvm-dep
Yes, I can remove that now

2023-01-10 20:51 UTC, kferles approved these changes
LGTM

2023-01-10 20:52 UTC, merged