Basic SARIF support in Vanguard [VAN-128]
Veridise/Vanguard pull request #46
Opened 2023-01-11 21:34 UTC by 0xddom

Draft of the SARIF module. I'm creating this PR early so we can discuss the design.

2023-01-11 21:40 UTC, kferles commented on lib/detectors/SARIF/SARIFLocation.h
> +namespace vanguard {
Can we add some comments above each class that describes the differences between these type of locations?

2023-01-11 21:41 UTC, kferles commented on lib/detectors/SARIF/SARIFLog.h
> +        std::vector<std::unique_ptr<SARIFRun>> runs;
Out of curiosity: what does a SARIFRun represent?

2023-01-11 21:42 UTC, 0xddom commented on lib/detectors/SARIF/SARIFLocation.h
> +namespace vanguard {
Yes! The standard has a good explanation of how they work. We can put it in the code for reference

2023-01-11 21:42 UTC, 0xddom commented on lib/detectors/SARIF/SARIFLog.h
> +        std::vector<std::unique_ptr<SARIFRun>> runs;
The execution of a particular tool. This way you can merge results of different tools into a single file

2023-01-11 21:51 UTC, 0xddom commented
Broadly, my design goals are:
- Have an object model that incrementally replicates SARIF but in a more readable manner
- Have the bare minimum we need to be considered as SARIF compliant in a first iteration and then expand on more SARIF features as we need
- Separate the object model from the serialization to potentially support multiple formats
  - Imagine a future where we decide to write the reports in BSON from the tools to the backend and reencode into JSON to the frontend
- Encapsulate the reporting inside the base `Detector`
  - Offer a public API to the subclasses (i.e. `Detector::alert(string message, string file, int line, int col, string name)`)
  - Detectors  would not need to override `report` as that method would change to just report all the results found.

2023-01-11 22:04 UTC, kferles commented
This looks good to me on a high level. One note: I would suggest having a DetectorAlert abstract class with a virtual method called toSARIFResult. This will give detectors the flexibility to create custom alerts and implement their conversion to SARIF. So, the public API you propose could be Detector::alert(DetectorAlert alert).

2023-01-12 00:01 UTC, Technius commented
I think a better location for the code is in `lib/SARIF`, and not `lib/detectors/SARIF`.

2023-01-12 00:12 UTC, Technius commented
It would be very helpful if you could set up a simple unit test in, say, `unit-tests/SARIFTests.cpp` to mock up how the API might be used.

2023-01-12 16:01 UTC, 0xddom commented
Yeah, missing headers in gcc that clang does not complain about

2023-01-12 16:03 UTC, 0xddom commented
So far you can tell how the serialization is intended to work

2023-01-12 18:30 UTC, Technius requested changes

2023-01-12 18:30 UTC, Technius commented on lib/SARIF/SARIF.h
> +    class SARIF {
This seems overly complicated. The data structure that represents the report/document should be independent of the file format(s) that it can be exported to.

2023-01-13 02:30 UTC, Technius commented
By the way, there seems to be an [official SARIF library for Python](https://github.com/microsoft/sarif-python-om), so we only need to implement the SARIF data structures for the C++ part of Vanguard.

2023-01-13 14:36 UTC, 0xddom commented
> By the way, there seems to be an [official SARIF library for Python](https://github.com/microsoft/sarif-python-om), so we only need to implement the SARIF data structures for the C++ part of Vanguard.

Yes, I checked for TPLs first. I plan to use it in the driver. Sadly no C/C++ version..

2023-01-18 15:54 UTC, 0xddom commented
All ready from my side

2023-01-18 19:11 UTC, kferles requested changes
Just delete the commented code and we are good to go!

2023-01-18 19:11 UTC, kferles commented on lib/Vanguard.cpp
> +//    const llvm::Module *module = modules.back();
Let's delete this comment.

2023-01-18 19:11 UTC, kferles commented on vanguard_driver.py
> +# def print_results(results):
Delete as well.

2023-01-18 19:11 UTC, kferles commented on vanguard_driver.py
> +    # if args.detector not in DETECTORS and args.detector != "all":
Delete as well.

2023-01-18 22:53 UTC, Technius commented on unit-tests/CMakeLists.txt
> +  "${CMAKE_CURRENT_BINARY_DIR}" "${CMAKE_INSTALL_INCLUDEDIR}"
Why is `CMAKE_INSTALL_INCLUDEDIR` needed here? Seems like `CMAKE_CURRENT_BINARY_DIR` should be sufficient.

2023-01-18 22:53 UTC, Technius commented on unit-tests/sarif-unittests.cpp
> +#include "../lib/SARIF/Message.h"
```suggestion
#include "SARIF/SARIF.h"
#include "SARIF/Message.h"
```

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/SARIF.h
> +    class SARIF {
nit: I think this can be replaced with `namespace SARIF` since there are no fields, and there is no code that creates an instance of a SARIF class.

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/formats/JSONSerializer.cpp
> +        return new rapidjson::Value(rapidjson::kObjectType);
nit: why not return `std::unique_ptr` for these methods?

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Log.h
> +        std::vector<std::unique_ptr<Run>> getRuns() {
nit: rename to indicate that the variable is being moved.
```suggestion
        std::vector<std::unique_ptr<Run>> takeRuns() {
```

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Log.h
> +        std::string getVersion() {
nit: 
```suggestion
        std::string getVersion() const {
```

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Message.h
> +        std::string getText() { return message; }
nit:
```suggestion
        std::string getText() const { return message; }
```

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Result.h
> +                locations(std::move(other.locations)) {};
This looks like a copy constructor, but it shouldn't be implemented like this because it moves the arguments. Why not leave this as the default copy constructor?

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Result.h
> +        std::string getSeverityLevel() {
nit:
```suggestion
        std::string getDetectorName() const { return detectorName; }
        std::string getSeverityLevel() const {
```

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Result.h
> +        std::vector<std::unique_ptr<Location>> getLocations() { return std::move(locations); }
I don't think these should move the variables, otherwise there's no way to "read" the result without modifying it.
```suggestion
        const Message *getMessage() const { return message.get(); }
        const std::vector<std::unique_ptr<Location>> &getLocations() const { return locations; }
```

If we really need some sort of move method, it would be better to rename (or copy) the current implementation as `takeMessage/Locations()`.

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Run.h
> +                results.push_back(std::move(x));
Note that this will leave a bunch of nullptrs in `newResults`. Should also call `newResults.clear()`.

2023-01-18 22:53 UTC, Technius commented on lib/SARIF/Serializer.h
> +        virtual OutFmt serialize(SARIF::Log &log) = 0;
I would make the parameters `const` because a reasonable expectation is that serialization will not modify the input data structures.
```suggestion
        virtual OutFmt serialize(const SARIF::Message &message) = 0;
        virtual OutFmt serialize(const SARIF::PhysLocation &physLocation) = 0;
        virtual OutFmt serialize(const SARIF::LogicLocation &logicLocation) = 0;
        virtual OutFmt serialize(const SARIF::Location &location) = 0;
        virtual OutFmt serialize(const SARIF::Result &result) = 0;
        virtual OutFmt serialize(const SARIF::Run &run) = 0;
        virtual OutFmt serialize(const SARIF::Log &log) = 0;
```

2023-01-18 22:53 UTC, Technius commented on lib/Vanguard.cpp
> +        rapidjson::FileWriteStream os(fp, writeBuffer, sizeof(writeBuffer));
I think it should be possible to use `rapidjson::BasicOStreamWrapper<std::ofstream>` here instead to avoid the C `FILE*`-related manual resource cleanup.

2023-01-18 22:53 UTC, Technius commented on lib/detectors/DetectorResult.h
> +        std::string getDetectorName() {
nit:
```suggestion
        std::string getDetectorName() const {
```

2023-01-18 22:54 UTC, Technius reviewed
Also, what is `test/sarif/sarif-2.1.0-rtm.4.json` used for?

2023-01-20 20:28 UTC, 0xddom commented
> Also, what is `test/sarif/sarif-2.1.0-rtm.4.json` used for?

I think it would be of interest to add an integration test that takes reports generated by the tool and check them against the schema. I left that there to build the test and I must have get distracted with other things and forget to implement it. We need an extra tool to do this checking and it must support JSON Schema Draft-04. I havent found one that works yet.

2023-01-23 22:16 UTC, Technius approved these changes
LGTM.

2023-01-23 22:16 UTC, Technius commented on lib/SARIF/Location.h
> +        [[nodiscard]] std::optional<const PhysLocation*> getPhysicalLocation() const {
nit: I think it's cleaner to return `PhysLocation*` (nullptr if nullopt). The additional optional seems unnecessary.

2023-01-23 22:16 UTC, Technius commented on lib/SARIF/Message.h
> +        std::string getText() const { return message; }
nit:
```suggestion
        [[nodiscard]] std::string getText() const { return message; }
```

2023-01-23 22:16 UTC, Technius commented on lib/SARIF/Location.h
> +        std::string getArtifactURI() const { return artifactURI; }
nit:
```suggestion
        [[nodiscard]] std::string getArtifactURI() const { return artifactURI; }
```

2023-01-23 22:16 UTC, Technius commented on lib/SARIF/Location.h
> +        std::string getName() const { return name; }
nit:
```suggestion
        [[nodiscard]] std::string getName() const { return name; }
```

2023-01-23 22:16 UTC, Technius commented on lib/SARIF/Serializer.h
> +    public:
Unless I'm mistaken, isn't a virtual destructor required?

2023-01-24 15:43 UTC, kferles approved these changes

2023-01-24 18:10 UTC, merged

2023-01-24 18:19 UTC, Technius commented
Regarding the JSON schema stuff, we can automatically generate Python classes & serialization/deserialization code using a library like https://github.com/koxudaxi/datamodel-code-generator . This also gives us validation for free.

2023-01-24 18:24 UTC, 0xddom commented
Right now the Python driver does not touch sarif. Everything is handled by the c++ tool. For now we could use something like that to write a simple testing script that takes the sarif report and either passes or fails a lit test (a la FileCheck).