Adding feature to identify modified contract variables
Veridise/Vanguard pull request #66
Opened 2023-02-07 02:45 UTC by stephensj2

2023-02-13 23:36 UTC, Technius reviewed
I don't know much about SVF but the high level idea looks okay to me.

2023-02-13 23:36 UTC, Technius commented on lib/analysis/SemanticValueSearch/ValueSearch.h
> +            SVF::SVFG* svfg = svfBuilder.buildFullSVFG(ander);
`svfg` is allocated by `buildFullSVFG`, but it is never deallocated; this will leak memory.

If we decide to plug this memory leak, we have to be careful to ensure that the results from `search()` cannot live longer than the `ValueSearch` instance that they were created from.

2023-02-13 23:36 UTC, Technius commented on lib/analysis/SemanticValueSearch/ValueSearch.h
> +                throw runtime_error("error");
This error message is not very useful, maybe something more descriptive?
```suggestion
                throw runtime_error("unhandled SVF node type");
```

2023-02-13 23:49 UTC, kferles requested changes

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/Instruction.h
> +            auto contract = this->block()->function()->contract();
```suggestion
            auto contract = this->contract();
```

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/Instruction.h
> +            auto contract = this->block()->function()->contract();
```suggestion
            auto contract = this->contract();
```

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/rust/near/NearModel.h
> +            return {};
Should we maybe throw a runtime exception?

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulModel.h
> +                if(call->getCalledFunction()->getName() == "convert_array_t_string_storage_to_t_string_memory_ptr") {
Not sure I understand this, but I haven't played with the yul frontend in a while.

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulModel.h
> +                //llvm::outs() << "Reads" << "\n";
Stray comment.

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulModel.h
> +                //llvm::outs() << "Writes" << "\n";
Stray comment.

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulStorageSearch.h
> +        std::vector<SVF::CxtDPItem> processIntrensic(const SVF::ContextCond *ctx, const SVF::VFGNode *node);
```suggestion
        std::vector<SVF::CxtDPItem> processIntrinsic(const SVF::ContextCond *ctx, const SVF::VFGNode *node);
```

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulStorageSearch.cpp
> +            //SVF::CxtDPItem src(sNode->getId(), *ctx);
Stray comment.

2023-02-13 23:49 UTC, kferles commented on lib/domain/libBlockchain/langs/yul/YulStorageSearch.cpp
> +        if (auto inst = llvm::dyn_cast<llvm::IntToPtrInst>(val)) {
I assume this logic is temporary, right?

2023-02-13 23:49 UTC, kferles commented on lib/analysis/SemanticValueSearch/ValueSearch.h
> +            SVF::SVFIRBuilder builder;
Can't we grab the pag, vfg, icfg, etc. from SVFUtils? 1. they are cached, so we compute them only once 2. we add domain cg edges.

2023-02-14 04:25 UTC, kferles approved these changes

2023-02-14 04:25 UTC, kferles commented
LGTM Thanks @stephensj2!

2023-02-14 15:54 UTC, merged