Taint Analysis ❤️ SVFUtils
Veridise/Vanguard pull request #80
Opened 2023-02-20 18:01 UTC by 0xddom

2023-02-20 19:53 UTC, kferles requested changes

2023-02-20 19:53 UTC, kferles commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +#if 0
Oh, these seem to be two different SVF-internal builders. Can we just create a `getTaintSVFG` which initializes and returns a different SVFG?

2023-02-21 09:05 UTC, 0xddom commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +#if 0
No, `TaintSVFGBuilder` is in SVF's namespace because it needs to be a friend of SVFG, but it is my custom class.

2023-02-21 15:37 UTC, kferles commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +#if 0
I see. Ok, I think we can still do what I suggested above.

2023-02-21 20:36 UTC, 0xddom commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +#if 0
But wasnt the point of moving the taint analysis svfg to utils for sharing? If we maintain two pointers changes in one SVFG will not replicate to the other

2023-02-21 20:40 UTC, 0xddom commented
Proposal: Refactor the TaintAnalysis module to use dependency injection, leaving to the user the decision of what SVFG to use. Also add a decorator that adds the TaintAnalysis specific modifications (globals and stuff) in case the user of the TaintAnalysis class needs them. If we run multiple detectors we may contaminate the global SVFG unless the decorator uses some kind of memento to rollback changes

2023-02-21 20:45 UTC, kferles commented on lib/analysis/interproc-analysis/SVFUtils.cpp
> +#if 0
Ok, let's merge it as is for now and we can decide late how to resolve this issue. I am not sure I understand the actual issue.

2023-02-21 20:45 UTC, kferles approved these changes

2023-02-21 20:48 UTC, merged