Create Unchecked Return Detector
Veridise/Vanguard pull request #93
Opened 2023-04-11 22:02 UTC by Sapo-Dorado

Detects return values from internal, external, or low level calls that aren't used. Will also support unused return values of library calls once Vanguard properly handles library calls.

2023-04-11 22:27 UTC, Technius requested changes

2023-04-11 22:27 UTC, Technius commented on test/Inputs/SafeMath.sol
> +// SPDX-License-Identifier: MIT
Is this a copy of OZ's SafeMath? The test environment should have a copy of OZ that can be passed as an include path to solc.

2023-04-11 22:27 UTC, Technius commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                if(contract->kind() == CONTRACT) {
Would it make sense to also check libraries?

2023-04-11 22:27 UTC, Technius commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +        void process(Function *fn) {
Need to skip the function if `fn->unwrap()` is null, or else we'll segfault when calling `fn->blocks()`.

We should definitely fix the program module so that it doesn't break randomly like this.

2023-04-11 22:27 UTC, Technius commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +#include<unordered_map>
A few includes are missing here, which will break IDE autocompletion. This can be debugged by temporarily adding a cpp file that includes this header.

2023-04-12 05:28 UTC, Sapo-Dorado commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +        void process(Function *fn) {
fixed in `detect()`

2023-04-12 21:13 UTC, benSepanski reviewed
Looks great. I had two small questions, but otherwise lgtm

2023-04-12 21:13 UTC, benSepanski commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                            process(fn);
Any chance this can be implemented as a `FunctionDetector`?

2023-04-12 21:13 UTC, benSepanski commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                     target = "an unspecified location";
If there are more than 1 targets, why do we just say "unspecified" rather than listing the targets?

2023-04-12 21:15 UTC, benSepanski commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                            process(fn);
TBH, I think our current handling of modules/functions as possibly null ought to be rethought.

@Technius I'd prefer that whenever we have a pointer in Vanguard, it is expected to be non-null. Maybe we can find a time to discuss re-designing the code base to rely on `optional`s for interface/abstract class handling?

2023-04-12 21:37 UTC, Sapo-Dorado commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                     target = "an unspecified location";
I wrote it this way because calls like the following test case make a call to an arbitrary address, so the targets are all of the available functions, which would spam the reporting and not reflect the fact that the target can be outside of the project.
```
function unchecked_call(address payable dst) public payable{
       dst.call{value:msg.value}("");
}
```
I did not consider the case where a call has multiple targets that are all relevant, so if these are important enough we can list all the targets.

2023-04-12 21:44 UTC, Technius commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                            process(fn);
Yes, let's discuss this synchronously.

2023-04-12 21:44 UTC, Technius approved these changes

2023-04-12 21:45 UTC, benSepanski commented on lib/detectors/Operations/UncheckedReturnDetector.h
> +                     target = "an unspecified location";
Seems like a reasonable decision to me, we can change later if necessary

2023-04-12 21:45 UTC, benSepanski approved these changes

2023-04-12 21:53 UTC, merged